Add https://arrayinamatrix.xyz
Graycot/loop-ring pull request #8
Opened 2023-05-06 03:06 UTC by array-in-a-matrix

2023-05-09 04:29 UTC, Graycot requested changes
Hey Array, I love the aesthetic of your website! Very cool. You also have a ton of different self-hosted services available which is great! 

Once you add the Loop Ring widget to your site, let me know and I'll approve your PR. **If I approved it without the widget on your site, the Loop Ring would break.**

Additionally, I recommend adding some site Tags and a Short Description. Early members of the ring have the metadata set to arbitrary 123 numbers because the ring used to only accept the site link, it has since been upgraded to accept other info as well. Over time I'll be manually updating those member's site info.

Cheers!

2023-05-10 19:04 UTC, array-in-a-matrix commented
Hii! Thanks for your kind words! I have added the widget to [my site](https://arrayinamatrix.xyz/index/webrings/) and added some descriptions.

2023-05-18 10:35 UTC, Graycot approved these changes

2023-05-18 10:39 UTC, Graycot approved these changes

2023-05-18 10:39 UTC, merged